config/routes.rb
ImpressOnRails::Application.routes.draw do

  namespace :admin do
    resources :presentations
  end

  namespace :admin do
    resources :slides
  end

  get 'presentations/:slug', to: 'presentations#show', as: :show_presentation
  get 'presentations', to: 'presentations#index'

  get '/admin', to: 'admin/presentations#index'

  get '/example', to: redirect('/example.html') 

  root to: 'application#index'

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
	has_many :slides

	validates :name, presence: true
end

app/models/slide.rb
class Slide < ActiveRecord::Base
	belongs_to :presentation

	validates :name, presence: true
	validates :presentation_id, presence: true
end

app/controllers/admin/presentations_controller.rb
module Admin
	class PresentationsController < AdminController
		
		def index
			@presentations = Presentation.all
		end

		def new
	    @presentation = Presentation.new
	  end

	  def edit
	  	@presentation = Presentation.find(params[:id])
	  end

	  def show
	  	@presentation = Presentation.find(params[:id])
	  end

	  def create
	    @presentation = Presentation.new(presentation_params)

	    if @presentation.save
	      redirect_to admin_presentation_path(@presentation), notice: 'Presentation was successfully created.'
	    else
	      render action: 'new'
	    end
	  end

	  def update
	  	@presentation = Presentation.find(params[:id])

	    if @presentation.update(presentation_params)
	      redirect_to admin_presentation_path(@presentation), notice: 'Presentation was successfully updated.'
	    else
	      render action: 'edit'
	    end
	  end

	  def destroy
	  	@presentation = Presentation.find(params[:id])

	    @presentation.destroy
	    redirect_to admin_presentations_url, notice: 'Presentation was successfully destroyed.'
	  end

	  private

	    def presentation_params
	      params.require(:presentation).permit(:name, :slug)
	    end
	end
end

app/controllers/admin/slides_controller.rb
module Admin
	class SlidesController < AdminController
		

		def new
	    @slide = Slide.new
	    @slide.presentation_id = params[:presentation_id]
	  end

	  def edit
	  	@slide = Slide.find(params[:id])
	  end

	  # def show
	  # 	@Slide = Slide.find(params[:id])
	  # end

	  def create
	    @slide = Slide.new(slide_params)

	    if @slide.save
	      redirect_to admin_presentation_path(@slide.presentation.id), notice: 'Slide was successfully created.'
	    else
	      render action: 'new'
	    end
	  end

	  def update
	  	@slide = Slide.find(params[:id])

	    if @slide.update(slide_params)
	      redirect_to admin_presentation_path(@slide.presentation.id), notice: 'Slide was successfully updated.'
	    else
	      render action: 'edit'
	    end
	  end

	  def destroy
	  	detail_id = @slide.presentation.id
	  	@slide = Slide.find(params[:id])

	    @slide.destroy
	    redirect_to admin_presentation_url(detail_id), notice: 'Slide was successfully destroyed.'
	  end

	  private

	    def slide_params
	      params.require(:slide).permit(:css_id, :sequence, :css_class, :name, :content, :presentation_id, :x, :y, :z, :rotate, :scale)
	    end
	end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  protect_from_forgery

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def index
  end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
	def index
		@presentations = Presentation.all
	end

	def show
		presentation = Presentation.find_by_slug(params[:slug])
		@slides = presentation.slides.order('sequence ASC')
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presentation_helper.rb
module PresentationHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/admin/presentations/_form.html.haml
- if @presentation.id
  = form_for @presentation, url: admin_presentation_path do |f|
    - if @presentation.errors.any?
      #error_explanation
        %h2= "#{pluralize(@presentation.errors.count, "error")} prohibited this presentation from being saved:"
        %ul
          - @presentation.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :slug
      = f.text_field :slug
    .clearfix

    .actions
      = link_to 'Show', admin_presentation_path(@presentation)
      = link_to 'Back', admin_presentations_path
      = f.submit 'Save'

- else 
  = form_for @presentation, url: admin_presentations_path do |f|
    - if @presentation.errors.any?
      #error_explanation
        %h2= "#{pluralize(@presentation.errors.count, "error")} prohibited this presentation from being saved:"
        %ul
          - @presentation.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :slug
      = f.text_field :slug
    .clearfix

    .actions
      = link_to 'Show', admin_presentation_path(@presentation)
      = link_to 'Back', admin_presentations_path
      = f.submit 'Save'

  

app/views/admin/presentations/edit.html.haml
%h4= "Editing Presentation "+@presentation.name

= render 'form'

app/views/admin/presentations/index.html.haml
%div.panel.panel-default
  
  %div.breadcrumb
    = "Listing Presentations"

  %table.table.table-hover
    %tr
      %th ID
      %th Name
      %th Actions

    - @presentations.each do |presentation|
      %tr
        %td= presentation.id
        %td= presentation.name
        %td
          = link_to 'Show', admin_presentation_path(presentation)
          = link_to 'Edit', edit_admin_presentation_path(presentation)
          = link_to 'Destroy', admin_presentation_path(presentation), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Presentation', new_admin_presentation_path

app/views/admin/presentations/new.html.haml
%h4 New Presentation

= render 'form'

= link_to 'Back', admin_presentations_path

app/views/admin/presentations/show.html.haml
%div.panel.panel-default
  
  %div.breadcrumb
    = "Presentation : "+@presentation.name
      
  %table.table.table-hover
    %tr
      %th ID
      %th Name
      %th CSS id 
      %th CSS class
      %th Content
      %th Actions

    - @presentation.slides.each do |slide|
      %tr
        %td= slide.id
        %td= slide.name
        %td= slide.css_id
        %td= slide.css_class
        %td= raw slide.content
        %td
          = link_to 'Edit', edit_admin_slide_path(slide)
          = link_to 'Destroy', admin_slide_path(slide), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Back', admin_presentations_path
= link_to 'New Slide', new_admin_slide_path(presentation_id: @presentation.id)

app/views/admin/slides/_form.html.haml
- if @slide.id
  = form_for @slide, url: admin_slide_path do |f|
    - if @slide.errors.any?
      #error_explanation
        %h2= "#{pluralize(@slide.errors.count, "error")} prohibited this slide from being saved:"
        %ul
          - @slide.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :sequence
      = f.text_field :sequence
    .field
      = f.label :css_id
      = f.text_field :css_id
    .field
      = f.label :css_class
      = f.text_field :css_class
    .clr
    %br
    .field
      = f.label :x
      = f.text_field :x
    .field
      = f.label :y
      = f.text_field :y
    .field
      = f.label :z
      = f.text_field :z
    .clr
    %br
    .field
      = f.label :rotate
      = f.text_field :rotate
    .field
      = f.label :scale
      = f.text_field :scale
    .clr

    .rich_text_edit
      = f.label :content
      = f.text_area :content, :class => 'ckeditor'

      = f.hidden_field :presentation_id, value: @slide.presentation_id
    .clr

    .actions
      = link_to 'Back', admin_presentation_path(@slide.presentation_id)
      = f.submit 'Save'

- else 
  = form_for @slide, url: admin_slides_path do |f|
    - if @slide.errors.any?
      #error_explanation
        %h2= "#{pluralize(@slide.errors.count, "error")} prohibited this slide from being saved:"
        %ul
          - @slide.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :sequence
      = f.text_field :sequence
    .field
      = f.label :css_id
      = f.text_field :css_id
    .field
      = f.label :css_class
      = f.text_field :css_class
    .clr
    %br
    .field
      = f.label :x
      = f.text_field :x
    .field
      = f.label :y
      = f.text_field :y
    .field
      = f.label :z
      = f.text_field :z
    .clr
    %br
    .field
      = f.label :rotate
      = f.text_field :rotate
    .field
      = f.label :scale
      = f.text_field :scale
    .clr
    

    .rich_text_edit
      = f.label :content
      = f.text_area :content, :class => 'ckeditor'

      = f.hidden_field :presentation_id, value: @slide.presentation_id
    .clr

    .actions
      = link_to 'Back', admin_presentation_path(@slide.presentation_id)
      = f.submit 'Save'

app/views/admin/slides/edit.html.haml
%h4= "Editing Slide "+@slide.try(:name)+" from presentation "+@slide.presentation.name

= render 'form'

app/views/admin/slides/new.html.haml
%h4 New Slide

= render 'form'

app/views/application/index.html.haml
#impress
  #title.step{data: {x: "0", y: "0", scale: "4"}}
    %span.try let's talk
    %h1 PHP testing
    %span.footnote possible time saver

  #its.step{data: {x: "850", y: "3000", rotate: "90", scale: "5"}}
    %p It's a <strong>presentation tool</strong> <br/>inspired by the idea behind <a href="http://prezi.com">prezi.com</a> <br/>and based on the <strong>power of CSS3 transforms and transitions</strong> in modern browsers.

  #big.step{data: {x: "3500", y: "2100", rotate: "180", scale: "6"}}
    %p visualize your <b>big</b> <span class="thoughts">thoughts</span>

  #tiny.step{data: {x: "2825", y: "1825", z: "-3000", rotate: "290", scale: "1"}}
    %p and <b>tiny</b> ideas

  #tiny2.step{data: {x: "2825", y: "2325", z: "-4000", rotate: "200", scale: "1"}}
    %p and <b>tiny</b> ideas

  #tiny3.step{data: {x: "2825", y: "2525", z: "-5000", rotate: "110", scale: "1"}}
    %p and <b>tiny</b> ideas

  #ing.step{data: {x: "3500", y: "-850", rotate: "270", scale: "6"}}
    %p by <b class="positioning">positioning</b>, <b class="rotating">rotating</b> and <b class="scaling">scaling</b> them on an infinite canvas

  #imagination.step{data: {x: "6700", y: "-300", scale: "6"}}
    %p the only <b>limit</b> is your <b class="imagination">imagination</b>

  #source.step{data: {x: "6300", y: "2000", scale: "4"}}
    %p want to know more?
    %q <a href="http://github.com/bartaz/impress.js">use the source</a>, Luke!

  #one-more-thing.step{data: {x: "7550", y: "-1400", scale: "3"}}
    %p one more thing...

  #its-in-3d.step{data: {x: "1600", y: "-2050", rotate: "270", scale: "6"}}
    %p <span class="have">have</span> <span class="you">you</span> <span class="noticed">noticed</span> <span class="its">it's</span> <span class="in">in</span> <b>3D<sup>*</sup></b>?
    %span.footnote * beat that, prezi ;)

  #about.step{data: {x: "4000", y: "4500", z: "100", scale: "4"}}
    %span.try For this presentation I used 
    %h1 impress.js
    %span.footnote inspiration from <a href="http://prezi.com/">prezi.com</a>

  #end.step{data: {x: "-1000", y: "3000", rotate: "90", scale: "4"}}
    %h1 Thx for you attention :)

  #overview.step{data: {x: "3000", y: "1500", scale: "10"}}

app/views/layouts/admin.html.haml
!!! 5
%html{lang: :en}

  %head

    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=1024"}
    %meta{name: "apple-mobile-web-app-capable", content: "yes"}

    %title Impress on Rails Administration

    = stylesheet_link_tag    "admin"
    = csrf_meta_tags

  %body.impress-not-supported

    %div.container.headline
      %h3= "Impress on Rails Administration"

    %div.container
      = yield

    = javascript_include_tag "admin"

app/views/layouts/application.html.haml
!!! 5
%html{lang: :en}

  %head

    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=1024"}
    %meta{name: "apple-mobile-web-app-capable", content: "yes"}

    %title Impress on Rails

    = stylesheet_link_tag    "application"
    = csrf_meta_tags

  %body.impress-not-supported

    = yield

    = javascript_include_tag "application"

app/views/presentations/index.html.haml
#impress

  - ex = ypsylon = rotate = 0
  - @presentations.each do |presentation|
    - (ex > 9000) ? ex -= 900 : ex += 900
    - (ypsylon > 6000) ? ypsylon -= 400 : ypsylon += 400
    - rotate += 90
    %div{id: presentation.slug, class: "step", data: {x: ex, y: ypsylon, rotate: rotate, scale: 4} }
      %p= link_to presentation.name, show_presentation_path(presentation.slug)
  
  #overview.step{data: {x: "3000", y: "1500", scale: "10"}}

app/views/presentations/show.html.haml
#impress

  - @slides.each do |slide|
    %div{id: slide.name, class: "step", data: {x: slide.x, y: slide.y, z: slide.z, rotate: slide.rotate, scale: slide.scale} }
      %p= raw slide.content
  
  #overview.step{data: {x: "3000", y: "1500", scale: "10"}}